/*  Copyright: AnandRathi IT Pvt. Ltd. This code is intellectual property of AnandRathi Group, and is protected by the relevant laws */
/**
* @param - NA
* @return -- NA
* @Name:- wealthStrategyConfigSlice
* @Type:- Functional Component
* @Role:- Create Slice for wealthStrategyConfig
* @Sprint:- Sprint 2.0 -- Jira 
* @Created by:- Bhojraj Singh Shekhawat
* @Created on:-  14-12-2023
* @Last Modified by:- No
* @Last modified on:- No
*/

import { createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit';

export interface ApplicationState {
    responseObject: {
        defaultCurrentWealth: string,
        minimumCurrentWealth: string,
        maximumCurrentWealth: string,
        defaultAnnualSaving: string,
        minimumAnnualSaving: string,
        maximumAnnualSaving: string,
        defaultTimeHorizon: string,
        minimumTimeHorizon: string,
        maximumTimeHorizon: string,
        equityAllocation: string,
        debtAllocation: string,
        defaultAnnualSavingPercentage: string,
        expectedEquityReturn: string,
        expectedDebtReturn: string,
        expectedportfolioreturns60: string,
        expectedportfolioreturns70: string,
        expectedportfolioreturns80: string,
        expectedportfolioreturns90: string,
        expectedportfolioreturns100: string,
        expectedportfolioreturnsNoPut60: string,
        expectedportfolioreturnsNoPut70: string,
        expectedportfolioreturnsNoPut80: string,
        expectedportfolioreturnsNoPut90: string,
        expectedportfolioreturnsNoPut100: string,
        directEquityandpms: string,
        equityMutualFunds: string,
        bankBalanceandFD: string,
        debtMutualFundsorBonds: string,
        defaultNiftyReturn: string,
        minNiftyReturn: string,
        maxNiftyReturn: string,
        adjustedequityallocationput60: string,
        adjustedequityallocationput70: string,
        adjustedequityallocationput80: string,
        adjustedequityallocationput90: string,
        adjustedequityallocationput100: string,
        adjustedequityallocationnoput60: string,
        adjustedequityallocationnoput70: string,
        adjustedequityallocationnoput80: string,
        adjustedequityallocationnoput90: string,
        adjustedequityallocationnoput100: string,
        adjusteddebtallocationput60: string,
        adjusteddebtallocationput70: string,
        adjusteddebtallocationput80: string,
        adjusteddebtallocationput90: string,
        adjusteddebtallocationput100: string,
        adjusteddebtallocationnoput60: string,
        adjusteddebtallocationnoput70: string,
        adjusteddebtallocationnoput80: string,
        adjusteddebtallocationnoput90: string,
        adjusteddebtallocationnoput100: string,
        revisedequityput60: string,
        revisedequityput70: string,
        revisedequityput80: string,
        revisedequityput90: string,
        revisedequityput100: string,
        revisedequitynoput60: string,
        revisedequitynoput70: string,
        revisedequitynoput80: string,
        revisedequitynoput90: string,
        revisedequitynoput100: string,
        reviseddebtput60: string,
        reviseddebtput70: string,
        reviseddebtput80: string,
        reviseddebtput90: string,
        reviseddebtput100: string,
        reviseddebtnoput60: string,
        reviseddebtnoput70: string,
        reviseddebtnoput80: string,
        reviseddebtnoput90: string,
        reviseddebtnoput100: string,
        equityMarketInsuranceCost: string,
        equityMarketInsuranceCostNoPut: string,
        minAmtWealthPortFolio: string,
        minAmtCashPortFolio: string,
        minAmtTaxSavingPortFolio: string,
        wealthPortFolioMidCapPercentage: string,
        wealthPortFolioLargeCapPercentage: string,
        minThresholdPercentage: string,
        wealthPortFolioLargeCapProductCount: string,
        wealthPortFolioMidCapProductCount: string,
        wealthPortFolioDebtProductCount: string,
        cashPortFolioProductCount: string,
        lastModifiedDateTime: string,
        wealthPortfolioJson: string,
        wealthPortfolioJsonNoPut: string,
        cashPortfolioJson: string,
        niftyJson: string,
        numberOfYearsForSensitivityAnalysis: string,
        debtMutualFundAlpha: string,
        savingGrowth: string,
        directEquityAndPMSGrowth: string,
        expectedPortfolioReturnPut20_60: string,
        expectedPortfolioReturnPut20_70: string,
        expectedPortfolioReturnPut20_80: string,
        expectedPortfolioReturnPut20_90: string,
        expectedPortfolioReturnPut20_100: string,
        adjustedEquityAllocationPut20_60: string,
        adjustedEquityAllocationPut20_70: string,
        adjustedEquityAllocationPut20_80: string,
        adjustedEquityAllocationPut20_90: string,
        adjustedEquityAllocationPut20_100: string,
        adjustedDebtAllocationPut20_60: string,
        adjustedDebtAllocationPut20_70: string,
        adjustedDebtAllocationPut20_80: string,
        adjustedDebtAllocationPut20_90: string,
        adjustedDebtAllocationPut20_100: string,
        revisedEquityPut20_60: string,
        revisedEquityPut20_70: string,
        revisedEquityPut20_80: string,
        revisedEquityPut20_90: string,
        revisedEquityPut20_100: string,
        revisedDebtPut20_60: string,
        revisedDebtPut20_70: string,
        revisedDebtPut20_80: string,
        revisedDebtPut20_90: string,
        niftyJsonPut20: string,
        productJsonPut20: string,
        titleput100: string,
        titleNoput: string,
        equityMarketInsuranceCostPut20: string,
        wealthPortfolioJsonWithPlanB: string,
        wealthPortfolioJsonNoPutWithPlanB: string,
        niftyJsonPutWithPlanB: string,
        niftyJsonNoPutWithPlanB: string,
        expectedSPMagnifierReturns: string,
        expectedSPAccelleratorReturns: string,
        spAllocation: string,
        expectedportfolioreturnsPutWithPlanB60: string,
        expectedportfolioreturnsPutWithPlanB70: string,
        expectedportfolioreturnsPutWithPlanB80: string,
        expectedportfolioreturnsPutWithPlanB90: string,
        expectedportfolioreturnsPutWithPlanB100: string,
        expectedportfolioreturnsNoPutWithPlanB60: string,
        expectedportfolioreturnsNoPutWithPlanB70: string,
        expectedportfolioreturnsNoPutWithPlanB80: string,
        expectedportfolioreturnsNoPutWithPlanB90: string,
        expectedportfolioreturnsNoPutWithPlanB100: string,
        adjustedequityallocationputWithPlanB60: string,
        adjustedequityallocationputWithPlanB70: string,
        adjustedequityallocationputWithPlanB80: string,
        adjustedequityallocationputWithPlanB90: string,
        adjustedequityallocationputWithPlanB100: string,
        adjustedequityallocationnoputWithPlanB60: string,
        adjustedequityallocationnoputWithPlanB70: string,
        adjustedequityallocationnoputWithPlanB80: string,
        adjustedequityallocationnoputWithPlanB90: string,
        adjustedequityallocationnoputWithPlanB100: string,
        adjusteddebtallocationputWithPlanB60: string,
        adjusteddebtallocationputWithPlanB70: string,
        adjusteddebtallocationputWithPlanB80: string,
        adjusteddebtallocationputWithPlanB90: string,
        adjusteddebtallocationputWithPlanB100: string,
        adjusteddebtallocationnoputWithPlanB60: string,
        adjusteddebtallocationnoputWithPlanB70: string,
        adjusteddebtallocationnoputWithPlanB80: string,
        adjusteddebtallocationnoputWithPlanB90: string,
        adjusteddebtallocationnoputWithPlanB100: string,
        dummyTextForPlanBVideo: string,
        descriptionput100: string,
        descriptionNoput: string,
        descriptionput20: string,
        niftyJsonWithoutPut: string,
        awssecretKey: string,
        wealthStrategyMinAmt: string,
        cashStrategyMinAmt: string,
        taxSavingPortFolioAmt: string,
        eqsttxrate: string,
        dsttxrate: string,
        dlttxrate: string,
        eqMFAlphaNNifty: string,
        eqMFAlphaPNifty: string,
        directEqAlphaPNifty: string,
        directEqAlphaNNifty: string,

        awsaccessKey: string,
        awsendPoint: string,
        awsendPointWRegion: string,
        awsendPointWRegionUSEast: string
    };
}

const initialState: ApplicationState = {
    responseObject: {
        defaultCurrentWealth: '',
        minimumCurrentWealth: '',
        maximumCurrentWealth: '',
        defaultAnnualSaving: '',
        minimumAnnualSaving: '',
        maximumAnnualSaving: '',
        defaultTimeHorizon: '',
        minimumTimeHorizon: '',
        maximumTimeHorizon: '',
        equityAllocation: '',
        debtAllocation: '',
        defaultAnnualSavingPercentage: '',
        expectedEquityReturn: '',
        expectedDebtReturn: '',
        expectedportfolioreturns60: '',
        expectedportfolioreturns70: '',
        expectedportfolioreturns80: '',
        expectedportfolioreturns90: '',
        expectedportfolioreturns100: '',
        expectedportfolioreturnsNoPut60: '',
        expectedportfolioreturnsNoPut70: '',
        expectedportfolioreturnsNoPut80: '',
        expectedportfolioreturnsNoPut90: '',
        expectedportfolioreturnsNoPut100: '',
        directEquityandpms: '',
        equityMutualFunds: '',
        bankBalanceandFD: '',
        debtMutualFundsorBonds: '',
        defaultNiftyReturn: '',
        minNiftyReturn: '',
        maxNiftyReturn: '',
        adjustedequityallocationput60: '',
        adjustedequityallocationput70: '',
        adjustedequityallocationput80: '',
        adjustedequityallocationput90: '',
        adjustedequityallocationput100: '',
        adjustedequityallocationnoput60: '',
        adjustedequityallocationnoput70: '',
        adjustedequityallocationnoput80: '',
        adjustedequityallocationnoput90: '',
        adjustedequityallocationnoput100: '',
        adjusteddebtallocationput60: '',
        adjusteddebtallocationput70: '',
        adjusteddebtallocationput80: '',
        adjusteddebtallocationput90: '',
        adjusteddebtallocationput100: '',
        adjusteddebtallocationnoput60: '',
        adjusteddebtallocationnoput70: '',
        adjusteddebtallocationnoput80: '',
        adjusteddebtallocationnoput90: '',
        adjusteddebtallocationnoput100: '',
        revisedequityput60: '',
        revisedequityput70: '',
        revisedequityput80: '',
        revisedequityput90: '',
        revisedequityput100: '',
        revisedequitynoput60: '',
        revisedequitynoput70: '',
        revisedequitynoput80: '',
        revisedequitynoput90: '',
        revisedequitynoput100: '',
        reviseddebtput60: '',
        reviseddebtput70: '',
        reviseddebtput80: '',
        reviseddebtput90: '',
        reviseddebtput100: '',
        reviseddebtnoput60: '',
        reviseddebtnoput70: '',
        reviseddebtnoput80: '',
        reviseddebtnoput90: '',
        reviseddebtnoput100: '',
        equityMarketInsuranceCost: '',
        equityMarketInsuranceCostNoPut: '',
        minAmtWealthPortFolio: '',
        minAmtCashPortFolio: '',
        minAmtTaxSavingPortFolio: '',
        wealthPortFolioMidCapPercentage: '',
        wealthPortFolioLargeCapPercentage: '',
        minThresholdPercentage: '',
        wealthPortFolioLargeCapProductCount: '',
        wealthPortFolioMidCapProductCount: '',
        wealthPortFolioDebtProductCount: '',
        cashPortFolioProductCount: '',
        lastModifiedDateTime: '',
        wealthPortfolioJson: '',
        wealthPortfolioJsonNoPut: '',
        cashPortfolioJson: '',
        niftyJson: '',
        numberOfYearsForSensitivityAnalysis: '',
        debtMutualFundAlpha: '',
        savingGrowth: '',
        directEquityAndPMSGrowth: '',
        expectedPortfolioReturnPut20_60: '',
        expectedPortfolioReturnPut20_70: '',
        expectedPortfolioReturnPut20_80: '',
        expectedPortfolioReturnPut20_90: '',
        expectedPortfolioReturnPut20_100: '',
        adjustedEquityAllocationPut20_60: '',
        adjustedEquityAllocationPut20_70: '',
        adjustedEquityAllocationPut20_80: '',
        adjustedEquityAllocationPut20_90: '',
        adjustedEquityAllocationPut20_100: '',
        adjustedDebtAllocationPut20_60: '',
        adjustedDebtAllocationPut20_70: '',
        adjustedDebtAllocationPut20_80: '',
        adjustedDebtAllocationPut20_90: '',
        adjustedDebtAllocationPut20_100: '',
        revisedEquityPut20_60: '',
        revisedEquityPut20_70: '',
        revisedEquityPut20_80: '',
        revisedEquityPut20_90: '',
        revisedEquityPut20_100: '',
        revisedDebtPut20_60: '',
        revisedDebtPut20_70: '',
        revisedDebtPut20_80: '',
        revisedDebtPut20_90: '',
        niftyJsonPut20: '',
        productJsonPut20: '',
        titleput100: '',
        titleNoput: '',
        equityMarketInsuranceCostPut20: '',
        wealthPortfolioJsonWithPlanB: '',
        wealthPortfolioJsonNoPutWithPlanB: '',
        niftyJsonPutWithPlanB: '',
        niftyJsonNoPutWithPlanB: '',
        expectedSPMagnifierReturns: '',
        expectedSPAccelleratorReturns: '',
        spAllocation: '',
        expectedportfolioreturnsPutWithPlanB60: '',
        expectedportfolioreturnsPutWithPlanB70: '',
        expectedportfolioreturnsPutWithPlanB80: '',
        expectedportfolioreturnsPutWithPlanB90: '',
        expectedportfolioreturnsPutWithPlanB100: '',
        expectedportfolioreturnsNoPutWithPlanB60: '',
        expectedportfolioreturnsNoPutWithPlanB70: '',
        expectedportfolioreturnsNoPutWithPlanB80: '',
        expectedportfolioreturnsNoPutWithPlanB90: '',
        expectedportfolioreturnsNoPutWithPlanB100: '',
        adjustedequityallocationputWithPlanB60: '',
        adjustedequityallocationputWithPlanB70: '',
        adjustedequityallocationputWithPlanB80: '',
        adjustedequityallocationputWithPlanB90: '',
        adjustedequityallocationputWithPlanB100: '',
        adjustedequityallocationnoputWithPlanB60: '',
        adjustedequityallocationnoputWithPlanB70: '',
        adjustedequityallocationnoputWithPlanB80: '',
        adjustedequityallocationnoputWithPlanB90: '',
        adjustedequityallocationnoputWithPlanB100: '',
        adjusteddebtallocationputWithPlanB60: '',
        adjusteddebtallocationputWithPlanB70: '',
        adjusteddebtallocationputWithPlanB80: '',
        adjusteddebtallocationputWithPlanB90: '',
        adjusteddebtallocationputWithPlanB100: '',
        adjusteddebtallocationnoputWithPlanB60: '',
        adjusteddebtallocationnoputWithPlanB70: '',
        adjusteddebtallocationnoputWithPlanB80: '',
        adjusteddebtallocationnoputWithPlanB90: '',
        adjusteddebtallocationnoputWithPlanB100: '',
        dummyTextForPlanBVideo: '',
        descriptionput100: '',
        descriptionNoput: '',
        descriptionput20: '',
        niftyJsonWithoutPut: '',
        awssecretKey: '',
        wealthStrategyMinAmt: '',
        cashStrategyMinAmt: '',
        taxSavingPortFolioAmt: '',
        eqsttxrate: '',
        dsttxrate: '',
        dlttxrate: '',
        eqMFAlphaNNifty: '',
        eqMFAlphaPNifty: '',
        directEqAlphaPNifty: '',
        directEqAlphaNNifty: '',

        awsaccessKey: '',
        awsendPoint: '',
        awsendPointWRegion: '',
        awsendPointWRegionUSEast: ''
    }
};

export const wealthStrategyConfig = createSlice({
    name: 'wealthStrategyConfig',
    initialState,
    reducers: {
        setWealthStrategyConfigData: (state, action: PayloadAction<any>) => {
            state.responseObject = action.payload;
            console.log('WealthStrategyConfigData aaya', state.responseObject);
        },

        logout: () => initialState,
    },
})

export const { setWealthStrategyConfigData } = wealthStrategyConfig.actions;
export default wealthStrategyConfig.reducer;